name: Metrics
on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:
  push:
    branches:
      - "master"
      - "main"

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    strategy:
      matrix:
        plugin:
          - { filename: "metrics.base.svg", token: "${{ secrets.METRICS_TOKEN }}", base: "header, activity, community, repositories", base_indepth: true, plugin_lines: yes, plugin_lines_delay: 30 }
          - { filename: "metrics.plugin.topics.svg", token: "NOT_NEEDED", base: "", plugin_topics: yes, plugin_topics_sort: stars, plugin_topics_limit: 20, plugin_topics_mode: icons }
          - { filename: "metrics.plugin.notable.svg", token: "${{ secrets.METRICS_TOKEN }}", base: "", plugin_notable: yes }
          - { filename: "metrics.plugin.leetcode.svg", token: "NOT_NEEDED", base: "", plugin_leetcode: yes, plugin_leetcode_sections: "solved, skills, recent" }
          - { filename: "metrics.plugin.fortune.svg", token: "NOT_NEEDED", base: "", plugin_fortune: yes }
          - { filename: "metrics.plugin.languages.indepth.svg", token: "${{ secrets.METRICS_TOKEN }}", base: "", plugin_languages: yes, plugin_languages_ignored: "html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot", plugin_languages_skipped: "pamaforce/dify", plugin_languages_indepth: yes, plugin_languages_details: "lines, percentage", plugin_languages_limit: 6, plugin_languages_analysis_timeout: 60 }
          - { filename: "metrics.plugin.languages.recent.svg", token: "${{ secrets.METRICS_TOKEN }}", base: "", plugin_languages: yes, plugin_languages_ignored: "html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot", plugin_languages_skipped: "pamaforce/dify", plugin_languages_sections: "recently-used", plugin_languages_details: "line, percentage", plugin_languages_limit: 4 }
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with: ${{ matrix.plugin }}
